services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - api

  api:
    restart: always
    build:
      context: ./
    depends_on:
      - mongo
      - redis
    expose:
      - 8001
    ports:
      - 8001:8001
    environment:
      NODE_ENV: dev
      SERVER_URL: localhost:8001
      PORT: 8001
      API_KEY: ${API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CORS_WHITELIST: http://localhost:8001,http://localhost:3000
      MONGODB_CONNECTION_STRING: mongodb://mongo:27017/chartlamp
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TLS: false
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}

  redis:
    restart: always
    image: redis:8
    ports:
      - 6379:6379
    expose:
      - 6379
  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017

volumes:
  mongo_data: