services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - express-mongo
      - react-express
    expose:
      - 3000
    environment:
      API_KEY: ${API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CORS_WHITELIST: http://localhost:5000,http://localhost:3000
      MONGODB_CONNECTION_STRING: mongodb://mongo:27017/test
      REDIS_HOST: redis
  redis:
    restart: always
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379
  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo
    ports:
      - 27017:27017
    expose:
      - 27017
networks:
  react-express:
  express-mongo:

volumes:
  mongo_data: