export const bodyParts = [
  "brain",
  "hypothalamus",
  "pituitary",
  "pineal body",
  "larynx",
  "oropharynx",
  "prostate",
  "epididymis",
  "testicles testes",
  "tongue",
  "oral cavity",
  "thymus",
  "parathyroids",
  "thyroid",
  "pancreas",
  "gallbladder",
  "bile ducts",
  "external genital organs male",
  "spleen",
  "anus",
  "rectum",
  "small intestine",
  "esophagus",
  "large intestine",
  "bladder and urethra",
  "bladder",
  "ureter",
  "intestine",
  "stomach",
  "spinal cord",
  "adrenal gland",
  "kidneys",
  "diapharagm",
  "liver",
  "heart",
  "lungs",
  "throat",
  "nose",
  "ear",
  "female cervix",
  "female fallopian tube",
  "female ovaries",
  "female vagina",
  "female breast",
  "left thigh",
  "right thigh",
  "pelvis bone",
  "ribs",
  "sacrum",
  "spinal cord",
  "skull",
];

 export const excludeWords = [
    "and",
    "the",
    "of",
    "in",
    "on",
    "at",
    "to",
    "for",
    "with",
    "by",
    "from",
    "as",
    "a",
    "an",
  ];