export const bodyParts = [
  "brain",
  "hypothalamus",
  "pituitary",
  "pineal body",
  "larynx",
  "oropharynx",
  "prostate",
  "epididymis",
  "testicles testes",
  "tongue",
  "oral cavity",
  "thymus",
  "parathyroids",
  "thyroid",
  "pancreas",
  "gallbladder",
  "bile ducts",
  "external genital organs male",
  "spleen",
  "anus",
  "rectum",
  "small intestine",
  "esophagus",
  "large intestine",
  "bladder and urethra",
  "bladder",
  "ureter",
  "intestine",
  "stomach",
  "spinal cord",
  "adrenal gland",
  "kidneys",
  "diapharagm",
  "liver",
  "heart",
  "lungs",
  "throat",
  "nose",
  "ear",
  "female cervix",
  "female fallopian tube",
  "female ovaries",
  "female vagina",
  "female breast",
  "left thigh",
  "right thigh",
  "pelvis bone",
  "ribs",
  "sacrum",
  "spinal cord",
  "skull",
  "skeleton",
  "tibia_fibula",
  "tarsal_metatarsal_phalanges",
  "humerus_ulna_radius",
  "ulna_radius",
  "metacarpal_metacarpus",
  "thorax_thoracic_vertebrae",
  "hair",
  "side eyes",
  "eyes",
  "blood stream",
  "veins",
  "lips",
  "cardio vascular system",
  "arteries",
  "artery of lower extremity",
  "artries of hip, thigh, knee, leg, foot",
  "artery of upper extremity",
  "female_hair",
];

export const excludeWords = [
  "and",
  "the",
  "of",
  "in",
  "on",
  "at",
  "to",
  "for",
  "with",
  "by",
  "from",
  "as",
  "a",
  "an",
];

export const CACHE_TTL = 86400;
