apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartlamp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chartlamp-api
  template:
    metadata:
      labels:
        app: chartlamp-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - api
      containers:
        - name: chartlamp-api
          image: <your_ecr_image_uri> 
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secrets
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
