name: Destroy Terraform Infra

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Init (remote backend)
      run: terraform init
      working-directory: terraform/

    - name: Destroy Infrastructure
      run: terraform destroy -auto-approve
      working-directory: terraform/
